## 2.2 neural net
 
![Let's start!](https://www.edureka.co/blog/wp-content/uploads/2017/07/Python-Numpy_05.gif)

In [2]:
import numpy as np

In [80]:
w0=np.array([[1,1,1],
            [0,0,0],
            [2,2,2]])

In [82]:
w1=np.array([[1,1,1],
             [1,1,1],
             [0,0,0]])

In [86]:
te=w0.dot(w1)
te

array([[2, 2, 2],
       [0, 0, 0],
       [4, 4, 4]])

In [83]:
def neu_net(inputs,weights):
  hid=inputs.dot(weights[0])
  pred=hid.dot(weights[1])
  return pred

In [ ]:
weights=np.array([w0,w1])
toes=np.array([1,1,1])
wins=np.array([1,1,1])
nfans=np.array([0,0,0])
inputs=np.array([toes[0],wins[0],nfans[0]])

In [ ]:
pred=neu_net(inputs,weights)
print(pred)

[2 2 2]


![mat](https://thumbs.gfycat.com/PositiveExhaustedAmericangoldfinch-size_restricted.gif)

In [ ]:
p=inputs.dot(w0)
print(p)
        

[1 1 1]


In [ ]:
([1,1,1])   ([[1,1,1],
              [1,1,1],
              [0,0,0]])

In [75]:
[2,2,2]

[2, 2, 2]

# 🌿 3d tensor

In [11]:
import torch

In [ ]:
vic=torch.ones(2,1,1)
vic

In [ ]:
t2=torch.tensor([[[0,0],
                  [1,1]],
 
                  [[3,3], 
                  [4,4]]])
t2.shape

In [78]:
torch.tensor([[[2]],
              [[2]]]).shape

torch.Size([2, 1, 1])

numpy to torch

In [ ]:
test=torch.from_numpy(w0)
test.type

In [90]:
big=torch.tensor([[2,2,2],
                  [1,1,1]])
b=torch.tensor([[1,1],
                [0,0],
                [2,2]])

In [89]:
bilal=torch.matmul(big,b)
bilal

tensor([[6, 6],
        [3, 3]])

In [92]:
ikka = np.array([[1,1],[1,2]])
type(ikka)

numpy.ndarray

In [ ]:
ikka=torch.from_numpy(ikka)
type(ikka)

In [95]:
bilalikka=torch.mm(bilal,ikka)
bilalikka

tensor([[12, 18],
        [ 6,  9]])