<a href="https://colab.research.google.com/github/gaai20/fpb/blob/master/_notebooks/2021-04-05-markdown.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 yoo

#multilayer  neural net

In [ ]:
import torch

In [ ]:
torch.manual_seed(7)
 
 
features=torch.Tensor([[0,1,1],[0,1,1]])
 
inlaye=features.view(1,6)

inlayer=inlaye.shape[1]
 
hidlay=2
 
outlay=1
 
w1=torch.randn((inlayer,hidlay))
 
w2=torch.randn((hidlay,outlay))
 
def sigmoid(x):
 
   return 1/1+(torch.exp(-x))
b1=torch.randn((1,1))
 
y=torch.mm(inlaye,w1)+b1
 

z=sigmoid(torch.mm(y,w2))

z

tensor([[1.9084]])

In [ ]:
p=torch.Tensor([[27,2],[3,3]])

q=torch.Tensor([[10,5],[3,3]])

In [ ]:
print(p+q)

tensor([[37.,  7.],
        [ 6.,  6.]])


martices;adition


# possible

*   1 * 1 + m * n

*   1 * m + h * m

*   m * n + m * n 


In [ ]:
e=torch.Tensor([[1,3,4],[1,2,1]])
print(e)

tensor([[1., 3., 4.],
        [1., 2., 1.]])


In [ ]:
t=e.view(1,6)
print(t)

tensor([[1., 3., 4., 1., 2., 1.]])
