In [2]:
import torch

In [3]:
def activation(x):
  
   return 1/(1+torch.exp(-x))

In [27]:
torch.manual_seed(7)
 
inp=torch.randn((1,4))
 
weight=torch.randn((4,2))
 
bias=torch.Tensor([1])

In [31]:
bias

tensor([1.])

In [29]:
y0=torch.matmul(inp,weight)
y0

tensor([[-0.7509, -0.6405]])

In [32]:
 
y0=activation(torch.matmul(inp,weight)+bias)
y0

tensor([[0.5619, 0.5889]])

Neural net
 
After a long break back to action with neural network, starting with udacity torch

Started with torch library ,sigmoid activation function , manual seed, random tensor, matrix multiplication, by combining all these we made a neural network